### Necessário para pegar o token    
### Post  
# @name loginAutenticado  
POST http://localhost:40000/Login HTTP/1.1  
content-type: application/json  
  
{      
    "UserName": "qwe",  
    "Password": "qwe"  
}  
### Seta o token  
@accessToken = {{loginAutenticado.response.body.$.token}}  
@username = {{loginAutenticado.response.body.$.username}}  


### teste de buscar todos os livros 
GET http://localhost:40000/GetAllLivros HTTP/1.1  
content-type: application/json  
Authorization: Bearer {{accessToken}}  

{      
    
}  

### teste de buscar livros por ID  
POST http://localhost:40000/GetLivrosByID HTTP/1.1  
content-type: application/json  
Authorization: Bearer {{accessToken}}   

{     
    "livroid": 1 
}  

### teste de inserção de livros  
POST http://localhost:40000/InsertLivros HTTP/1.1  
content-type: application/json  
Authorization:  Bearer {{accessToken}} 

{   
    "titulo": "O Senhor dos Anéis",
    "autor": "J.R.R. Tolkien",
    "anopublicacao": 1954,
    "genero": "Fantasia"
}  

### teste de atualização de livros  
POST http://localhost:40000/UpdateLivros HTTP/1.1  
content-type: application/json  
Authorization: Bearer {{accessToken}}

{      
    "livroid": 1,
    "titulo": "O Senhor dos Anais",
    "autor": "J.R.R. Tolkien",
    "anopublicacao": 2015,
    "genero": "+18",
    "removido": false
}  

### teste de deleção de livros
POST http://localhost:40000/DeleteLivros HTTP/1.1  
content-type: application/json  
Authorization: Bearer {{accessToken}}

{      
    "livroid": 2 
}  
